/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventSchema extends BaseModel {
  static $columns = ['clientIp', 'durationMs', 'id', 'method', 'path', 'serverId', 'service', 'source', 'statusCode', 'ts'] as const
  $columns = EventSchema.$columns
  @column()
  declare clientIp: string | null
  @column()
  declare durationMs: number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare method: string | null
  @column()
  declare path: string | null
  @column()
  declare serverId: number
  @column()
  declare service: string | null
  @column()
  declare source: string
  @column()
  declare statusCode: number | null
  @column.dateTime()
  declare ts: DateTime
}

export class IncidentSchema extends BaseModel {
  static $columns = ['clientIp', 'createdAt', 'hits', 'id', 'rule', 'samplePath', 'serverId'] as const
  $columns = IncidentSchema.$columns
  @column()
  declare clientIp: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare hits: number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare rule: string
  @column()
  declare samplePath: string | null
  @column()
  declare serverId: number
}

export class ServerSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ingestKeyHash', 'lastSeenAt', 'name'] as const
  $columns = ServerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ingestKeyHash: string
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare name: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
